--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.2.280.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 24/11/2014 21:05:13
-- Server version: 5.1.73-community
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO sgg.aluno(codigo, matricula, nome, telefone, sexo, cpf, dataNascimento, email, endereco_fk) VALUES
(1, '123', 'Katyelen', '(32)8829-3197', '', '', '', '', NULL);
INSERT INTO sgg.aluno(codigo, matricula, nome, telefone, sexo, cpf, dataNascimento, email, endereco_fk) VALUES
(2, '39857398', 'hhjbhj', '(__)____-____', 'Feminino', '897.887.677-67', '87/86/8878', 'nghyugyhjug', 4);