--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.2.280.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/11/2014 17:36:23
-- Server version: 5.1.73-community
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO sgg.endereco(codigo, endereco, bairro, cep, cidade) VALUES
(1, 'Av. Dr. simeão de Faria', 'Santa Cruz', '36088-000', 'JF');
INSERT INTO sgg.endereco(codigo, endereco, bairro, cep, cidade) VALUES
(2, 'Av .Dr. Simeão de Faria, 1425', 'Santa Cruz', '36088-000', 'JF');
INSERT INTO sgg.endereco(codigo, endereco, bairro, cep, cidade) VALUES
(3, 'dfgdfg', 'fdgfdg', '_____-___', 'JF');
INSERT INTO sgg.endereco(codigo, endereco, bairro, cep, cidade) VALUES
(4, 'njk', 'hjhjk', '_____-___', 'jknh');
INSERT INTO sgg.endereco(codigo, endereco, bairro, cep, cidade) VALUES
(5, '', '', '_____-___', '');
INSERT INTO sgg.endereco(codigo, endereco, bairro, cep, cidade) VALUES
(6, '', '', '_____-___', '');
INSERT INTO sgg.endereco(codigo, endereco, bairro, cep, cidade) VALUES
(7, '', '', '_____-___', '0');
INSERT INTO sgg.endereco(codigo, endereco, bairro, cep, cidade) VALUES
(8, '', '', '_____-___', '0');
INSERT INTO sgg.endereco(codigo, endereco, bairro, cep, cidade) VALUES
(9, '', '', '_____-___', '');