--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.2.280.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/11/2014 17:36:24
-- Server version: 5.1.73-community
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO sgg.equipamento(codigo, nome, grupoMuscular_fk) VALUES
(1, 'LEG PRESS', 1);
INSERT INTO sgg.equipamento(codigo, nome, grupoMuscular_fk) VALUES
(2, 'MESA FLEXORA', 1);
INSERT INTO sgg.equipamento(codigo, nome, grupoMuscular_fk) VALUES
(3, 'PULLEY COSTAS', 2);
INSERT INTO sgg.equipamento(codigo, nome, grupoMuscular_fk) VALUES
(4, 'REMADA ALTA', 3);
INSERT INTO sgg.equipamento(codigo, nome, grupoMuscular_fk) VALUES
(5, 'SUPINO', 7);
INSERT INTO sgg.equipamento(codigo, nome, grupoMuscular_fk) VALUES
(6, 'ROSCA DIRETA', 4);
INSERT INTO sgg.equipamento(codigo, nome, grupoMuscular_fk) VALUES
(7, 'CROSS-OVER', 6);
INSERT INTO sgg.equipamento(codigo, nome, grupoMuscular_fk) VALUES
(8, 'ELEVAÇÃO LATERAL', 3);
INSERT INTO sgg.equipamento(codigo, nome, grupoMuscular_fk) VALUES
(9, 'TRÍCEPS MÁQUINA', 7);
INSERT INTO sgg.equipamento(codigo, nome, grupoMuscular_fk) VALUES
(10, 'HACK', 8);
INSERT INTO sgg.equipamento(codigo, nome, grupoMuscular_fk) VALUES
(11, 'ABDOMINAL', 5);
INSERT INTO sgg.equipamento(codigo, nome, grupoMuscular_fk) VALUES
(12, 'CADEIRA ABDUTORA', 1);
INSERT INTO sgg.equipamento(codigo, nome, grupoMuscular_fk) VALUES
(13, 'CADEIRA EXTENSORA', 1);
INSERT INTO sgg.equipamento(codigo, nome, grupoMuscular_fk) VALUES
(14, 'AGACHAMENTO', 1);