--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.2.280.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/11/2014 17:36:25
-- Server version: 5.1.73-community
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO sgg.grupomuscular(codigo, grupo) VALUES
(1, 'PERNA');
INSERT INTO sgg.grupomuscular(codigo, grupo) VALUES
(2, 'COSTAS');
INSERT INTO sgg.grupomuscular(codigo, grupo) VALUES
(3, 'OMBRO');
INSERT INTO sgg.grupomuscular(codigo, grupo) VALUES
(4, 'BÍCEPS');
INSERT INTO sgg.grupomuscular(codigo, grupo) VALUES
(5, 'ABDOME');
INSERT INTO sgg.grupomuscular(codigo, grupo) VALUES
(6, 'PEITORAL');
INSERT INTO sgg.grupomuscular(codigo, grupo) VALUES
(7, 'TRÍCEPS');
INSERT INTO sgg.grupomuscular(codigo, grupo) VALUES
(8, 'GLÚTEOS');