--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.2.280.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/11/2014 17:36:26
-- Server version: 5.1.73-community
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO sgg.horario(codigo, aluno_fk, diaSemana, entrada, saida, local, turma_fk) VALUES
(1, '123', 'Segunda', '19:15', '20:05', 'Sala 1', '1');
INSERT INTO sgg.horario(codigo, aluno_fk, diaSemana, entrada, saida, local, turma_fk) VALUES
(2, '123', 'Quarta', '18:15', '17:05', 'Sala 1', '2');