--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.2.280.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/11/2014 17:36:27
-- Server version: 5.1.73-community
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO sgg.mensalidade(codigo, aluno_fk, dataVencimento, valor, historico) VALUES
(1, '123', '15/12/2014', 85.00, 'Mensalidade Ref.: DEZ/2014');
INSERT INTO sgg.mensalidade(codigo, aluno_fk, dataVencimento, valor, historico) VALUES
(2, '123', '15/11/2014', 85.00, 'Mensalidade Ref.: NOV/2014');
INSERT INTO sgg.mensalidade(codigo, aluno_fk, dataVencimento, valor, historico) VALUES
(3, '123', '15/10/2014', 85.00, 'Mensalidade Ref.: OUT/2014');
INSERT INTO sgg.mensalidade(codigo, aluno_fk, dataVencimento, valor, historico) VALUES
(4, '123', '15/09/2014', 85.00, 'Mensalidade Ref.: SET/2014');