--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.2.280.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/11/2014 17:36:28
-- Server version: 5.1.73-community
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO sgg.perimetro(codigo, aluno_fk, dataAvaliacao, bracoDir, bracoEsq, anteBDir, anteBEsq, torax, cintura, abdome, quadril, coxaDir, coxaEsq, pantDir, pantEsq) VALUES
(2, 123, '', 25.00, 25.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00);