--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.2.280.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/11/2014 17:36:30
-- Server version: 5.1.73-community
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO sgg.pessoa(codigo, tipo_fk, matricula, nome, telefone, sexo, cpf, dataNascimento, email, endereco_fk, numeroCartao, Situacao) VALUES
(1, '1', 123, 'Katyelen', '(__)____-____', 'Feminino', '___.___.___-__', '', '', 8, '123456789', 'ATIVO');
INSERT INTO sgg.pessoa(codigo, tipo_fk, matricula, nome, telefone, sexo, cpf, dataNascimento, email, endereco_fk, numeroCartao, Situacao) VALUES
(2, '4', 456, 'Luciano', '(__)____-____', 'Masculino', '___.___.___-__', '', '', 9, '123456789', 'ATIVO');