
CREATE DATABASE sgg
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.2.280.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/11/2014 17:34:54
-- Server version: 5.1.73-community
-- Client version: 4.1
--


-- 
-- Set default database
--
USE sgg;

--
-- Definition for table aluno
--
DROP TABLE aluno;
CREATE TABLE aluno (
  codigo int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  matricula varchar(60) DEFAULT NULL,
  nome varchar(255) DEFAULT NULL,
  telefone varchar(25) DEFAULT NULL,
  sexo varchar(10) DEFAULT NULL,
  cpf varchar(20) DEFAULT NULL,
  dataNascimento varchar(10) DEFAULT NULL,
  email varchar(50) DEFAULT NULL,
  endereco_fk int(11) DEFAULT NULL,
  PRIMARY KEY (codigo)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET latin1
COLLATE latin1_swedish_ci
COMMENT = 'tabela de aluno';

--
-- Definition for table endereco
--
DROP TABLE endereco;
CREATE TABLE endereco (
  codigo int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  endereco varchar(255) DEFAULT NULL,
  bairro varchar(100) DEFAULT NULL,
  cep varchar(15) DEFAULT NULL,
  cidade varchar(100) DEFAULT NULL,
  PRIMARY KEY (codigo)
)
ENGINE = INNODB
AUTO_INCREMENT = 10
AVG_ROW_LENGTH = 1820
CHARACTER SET latin1
COLLATE latin1_swedish_ci
COMMENT = 'tabela de endereco';

--
-- Definition for table equipamento
--
DROP TABLE equipamento;
CREATE TABLE equipamento (
  codigo int(11) NOT NULL AUTO_INCREMENT,
  nome varchar(30) NOT NULL,
  grupoMuscular_fk int(11) DEFAULT NULL,
  PRIMARY KEY (codigo)
)
ENGINE = INNODB
AUTO_INCREMENT = 15
AVG_ROW_LENGTH = 1170
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table grupomuscular
--
DROP TABLE grupomuscular;
CREATE TABLE grupomuscular (
  codigo int(11) NOT NULL AUTO_INCREMENT,
  grupo varchar(30) NOT NULL,
  PRIMARY KEY (codigo)
)
ENGINE = INNODB
AUTO_INCREMENT = 9
AVG_ROW_LENGTH = 2048
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table horario
--
DROP TABLE horario;
CREATE TABLE horario (
  codigo int(11) NOT NULL AUTO_INCREMENT,
  aluno_fk varchar(30) DEFAULT NULL,
  diaSemana varchar(30) DEFAULT NULL,
  entrada varchar(30) DEFAULT NULL,
  saida varchar(30) DEFAULT NULL,
  local varchar(40) DEFAULT NULL,
  turma_fk varchar(30) DEFAULT NULL,
  PRIMARY KEY (codigo)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table mensalidade
--
DROP TABLE mensalidade;
CREATE TABLE mensalidade (
  codigo int(11) NOT NULL AUTO_INCREMENT,
  aluno_fk varchar(40) NOT NULL,
  dataVencimento varchar(25) NOT NULL,
  valor decimal(5, 2) DEFAULT NULL,
  historico varchar(100) DEFAULT NULL,
  PRIMARY KEY (codigo)
)
ENGINE = INNODB
AUTO_INCREMENT = 9
AVG_ROW_LENGTH = 4096
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table perimetro
--
DROP TABLE perimetro;
CREATE TABLE perimetro (
  codigo int(11) NOT NULL AUTO_INCREMENT,
  aluno_fk int(11) NOT NULL,
  dataAvaliacao varchar(20) NOT NULL,
  bracoDir decimal(5, 2) DEFAULT NULL,
  bracoEsq decimal(5, 2) DEFAULT NULL,
  anteBDir decimal(5, 2) DEFAULT NULL,
  anteBEsq decimal(5, 2) DEFAULT NULL,
  torax decimal(5, 2) DEFAULT NULL,
  cintura decimal(5, 2) DEFAULT NULL,
  abdome decimal(5, 2) DEFAULT NULL,
  quadril decimal(5, 2) DEFAULT NULL,
  coxaDir decimal(5, 2) DEFAULT NULL,
  coxaEsq decimal(5, 2) DEFAULT NULL,
  pantDir decimal(5, 2) DEFAULT NULL,
  pantEsq decimal(5, 2) DEFAULT NULL,
  PRIMARY KEY (codigo)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table pessoa
--
DROP TABLE pessoa;
CREATE TABLE pessoa (
  codigo int(11) NOT NULL AUTO_INCREMENT,
  tipo_fk varbinary(25) DEFAULT NULL,
  matricula int(11) NOT NULL,
  nome varchar(100) NOT NULL,
  telefone varchar(20) NOT NULL,
  sexo varchar(20) NOT NULL,
  cpf varchar(20) NOT NULL,
  dataNascimento varchar(20) NOT NULL,
  email varchar(100) NOT NULL,
  endereco_fk int(11) DEFAULT NULL,
  numeroCartao varchar(40) DEFAULT NULL,
  Situacao varchar(20) DEFAULT NULL,
  PRIMARY KEY (codigo)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tipo
--
DROP TABLE tipo;
CREATE TABLE tipo (
  codigo int(11) NOT NULL AUTO_INCREMENT,
  descricao varchar(50) NOT NULL,
  PRIMARY KEY (codigo)
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 3276
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table treino
--
DROP TABLE treino;
CREATE TABLE treino (
  codigo int(11) NOT NULL AUTO_INCREMENT,
  aluno_fk varbinary(25) NOT NULL,
  ordem int(11) NOT NULL,
  equipamento_fk int(11) NOT NULL,
  serie int(11) NOT NULL,
  repeticao int(11) NOT NULL,
  carga int(11) NOT NULL,
  PRIMARY KEY (codigo)
)
ENGINE = INNODB
AUTO_INCREMENT = 9
AVG_ROW_LENGTH = 2048
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table turma
--
DROP TABLE turma;
CREATE TABLE turma (
  codigo int(11) NOT NULL AUTO_INCREMENT,
  turma varchar(50) NOT NULL,
  PRIMARY KEY (codigo)
)
ENGINE = INNODB
AUTO_INCREMENT = 14
AVG_ROW_LENGTH = 1260
CHARACTER SET latin1
COLLATE latin1_swedish_ci;