--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.2.280.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/11/2014 17:36:31
-- Server version: 5.1.73-community
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO sgg.tipo(codigo, descricao) VALUES
(1, 'Aluno');
INSERT INTO sgg.tipo(codigo, descricao) VALUES
(2, 'Funcionário');
INSERT INTO sgg.tipo(codigo, descricao) VALUES
(3, 'Professor');
INSERT INTO sgg.tipo(codigo, descricao) VALUES
(4, 'Personal');
INSERT INTO sgg.tipo(codigo, descricao) VALUES
(5, 'Secretaria');