--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.2.280.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/11/2014 17:36:32
-- Server version: 5.1.73-community
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO sgg.treino(codigo, aluno_fk, ordem, equipamento_fk, serie, repeticao, carga) VALUES
(1, '123', 1, 1, 3, 10, 100);
INSERT INTO sgg.treino(codigo, aluno_fk, ordem, equipamento_fk, serie, repeticao, carga) VALUES
(2, '123', 2, 2, 3, 10, 25);
INSERT INTO sgg.treino(codigo, aluno_fk, ordem, equipamento_fk, serie, repeticao, carga) VALUES
(3, '123', 3, 10, 3, 12, 20);
INSERT INTO sgg.treino(codigo, aluno_fk, ordem, equipamento_fk, serie, repeticao, carga) VALUES
(4, '123', 4, 12, 3, 12, 40);
INSERT INTO sgg.treino(codigo, aluno_fk, ordem, equipamento_fk, serie, repeticao, carga) VALUES
(5, '123', 5, 4, 3, 15, 10);
INSERT INTO sgg.treino(codigo, aluno_fk, ordem, equipamento_fk, serie, repeticao, carga) VALUES
(6, '123', 6, 9, 3, 12, 20);
INSERT INTO sgg.treino(codigo, aluno_fk, ordem, equipamento_fk, serie, repeticao, carga) VALUES
(7, '123', 7, 11, 3, 30, 0);
INSERT INTO sgg.treino(codigo, aluno_fk, ordem, equipamento_fk, serie, repeticao, carga) VALUES
(8, '', 15, 4, 15, 3, 5);