--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.2.280.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/11/2014 17:36:33
-- Server version: 5.1.73-community
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO sgg.turma(codigo, turma) VALUES
(1, 'MUSCULACAO');
INSERT INTO sgg.turma(codigo, turma) VALUES
(2, 'DANÇA');
INSERT INTO sgg.turma(codigo, turma) VALUES
(3, 'PILATES');
INSERT INTO sgg.turma(codigo, turma) VALUES
(4, 'SPINNING');
INSERT INTO sgg.turma(codigo, turma) VALUES
(5, 'COMBAT TRAINER');
INSERT INTO sgg.turma(codigo, turma) VALUES
(6, 'ZUMBA');
INSERT INTO sgg.turma(codigo, turma) VALUES
(7, 'ALONGAMENTO');
INSERT INTO sgg.turma(codigo, turma) VALUES
(8, 'KANGOO');
INSERT INTO sgg.turma(codigo, turma) VALUES
(9, 'JUMP');
INSERT INTO sgg.turma(codigo, turma) VALUES
(10, 'ZUMBA');
INSERT INTO sgg.turma(codigo, turma) VALUES
(11, 'CORRIDA');
INSERT INTO sgg.turma(codigo, turma) VALUES
(12, 'MMA');
INSERT INTO sgg.turma(codigo, turma) VALUES
(13, 'JUDÔ');